/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdministracaoRouteImport } from './routes/administracao'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AvisosRouteImport } from './routes/avisos'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as CaixaRouteImport } from './routes/caixa'
import { Route as EstudoRouteImport } from './routes/estudo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MaisRouteImport } from './routes/mais'
import { Route as MinisteriosRouteImport } from './routes/ministerios'
import { Route as OracaoRouteImport } from './routes/oracao'
import { Route as PastoralRouteImport } from './routes/pastoral'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AdminAvisosRouteImport } from './routes/admin.avisos'
import { Route as AdminMembrosRouteImport } from './routes/admin.membros'
import { Route as CultoDiaRouteImport } from './routes/culto.$dia'
import { Route as MinisteriosIndexRouteImport } from './routes/ministerios.index'
import { Route as MinisteriosSlugIndexRouteImport } from './routes/ministerios.$slug.index'
import { Route as MinisteriosSlugSecaoRouteImport } from './routes/ministerios.$slug.$secao'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministracaoRoute = AdministracaoRouteImport.update({
  id: '/administracao',
  path: '/administracao',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisosRoute = AvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const CaixaRoute = CaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudoRoute = EstudoRouteImport.update({
  id: '/estudo',
  path: '/estudo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MaisRoute = MaisRouteImport.update({
  id: '/mais',
  path: '/mais',
  getParentRoute: () => rootRouteImport,
} as any)
const MinisteriosRoute = MinisteriosRouteImport.update({
  id: '/ministerios',
  path: '/ministerios',
  getParentRoute: () => rootRouteImport,
} as any)
const OracaoRoute = OracaoRouteImport.update({
  id: '/oracao',
  path: '/oracao',
  getParentRoute: () => rootRouteImport,
} as any)
const PastoralRoute = PastoralRouteImport.update({
  id: '/pastoral',
  path: '/pastoral',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminAvisosRoute = AdminAvisosRouteImport.update({
  id: '/admin/avisos',
  path: '/admin/avisos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMembrosRoute = AdminMembrosRouteImport.update({
  id: '/admin/membros',
  path: '/admin/membros',
  getParentRoute: () => rootRouteImport,
} as any)
const CultoDiaRoute = CultoDiaRouteImport.update({
  id: '/culto/$dia',
  path: '/culto/$dia',
  getParentRoute: () => rootRouteImport,
} as any)
const MinisteriosIndexRoute = MinisteriosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MinisteriosRoute,
} as any)
const MinisteriosSlugIndexRoute = MinisteriosSlugIndexRouteImport.update({
  id: '/$slug/',
  path: '/$slug/',
  getParentRoute: () => MinisteriosRoute,
} as any)
const MinisteriosSlugSecaoRoute = MinisteriosSlugSecaoRouteImport.update({
  id: '/$slug/$secao',
  path: '/$slug/$secao',
  getParentRoute: () => MinisteriosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administracao': typeof AdministracaoRoute
  '/agenda': typeof AgendaRoute
  '/avisos': typeof AvisosRoute
  '/cadastro': typeof CadastroRoute
  '/caixa': typeof CaixaRoute
  '/estudo': typeof EstudoRoute
  '/login': typeof LoginRoute
  '/mais': typeof MaisRoute
  '/ministerios': typeof MinisteriosRouteWithChildren
  '/oracao': typeof OracaoRoute
  '/pastoral': typeof PastoralRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/admin/avisos': typeof AdminAvisosRoute
  '/admin/membros': typeof AdminMembrosRoute
  '/culto/$dia': typeof CultoDiaRoute
  '/ministerios/': typeof MinisteriosIndexRoute
  '/ministerios/$slug/$secao': typeof MinisteriosSlugSecaoRoute
  '/ministerios/$slug/': typeof MinisteriosSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/administracao': typeof AdministracaoRoute
  '/agenda': typeof AgendaRoute
  '/avisos': typeof AvisosRoute
  '/cadastro': typeof CadastroRoute
  '/caixa': typeof CaixaRoute
  '/estudo': typeof EstudoRoute
  '/login': typeof LoginRoute
  '/mais': typeof MaisRoute
  '/oracao': typeof OracaoRoute
  '/pastoral': typeof PastoralRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/admin/avisos': typeof AdminAvisosRoute
  '/admin/membros': typeof AdminMembrosRoute
  '/culto/$dia': typeof CultoDiaRoute
  '/ministerios': typeof MinisteriosIndexRoute
  '/ministerios/$slug/$secao': typeof MinisteriosSlugSecaoRoute
  '/ministerios/$slug': typeof MinisteriosSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/administracao': typeof AdministracaoRoute
  '/agenda': typeof AgendaRoute
  '/avisos': typeof AvisosRoute
  '/cadastro': typeof CadastroRoute
  '/caixa': typeof CaixaRoute
  '/estudo': typeof EstudoRoute
  '/login': typeof LoginRoute
  '/mais': typeof MaisRoute
  '/ministerios': typeof MinisteriosRouteWithChildren
  '/oracao': typeof OracaoRoute
  '/pastoral': typeof PastoralRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/admin/avisos': typeof AdminAvisosRoute
  '/admin/membros': typeof AdminMembrosRoute
  '/culto/$dia': typeof CultoDiaRoute
  '/ministerios/': typeof MinisteriosIndexRoute
  '/ministerios/$slug/$secao': typeof MinisteriosSlugSecaoRoute
  '/ministerios/$slug/': typeof MinisteriosSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administracao'
    | '/agenda'
    | '/avisos'
    | '/cadastro'
    | '/caixa'
    | '/estudo'
    | '/login'
    | '/mais'
    | '/ministerios'
    | '/oracao'
    | '/pastoral'
    | '/perfil'
    | '/admin/avisos'
    | '/admin/membros'
    | '/culto/$dia'
    | '/ministerios/'
    | '/ministerios/$slug/$secao'
    | '/ministerios/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/administracao'
    | '/agenda'
    | '/avisos'
    | '/cadastro'
    | '/caixa'
    | '/estudo'
    | '/login'
    | '/mais'
    | '/oracao'
    | '/pastoral'
    | '/perfil'
    | '/admin/avisos'
    | '/admin/membros'
    | '/culto/$dia'
    | '/ministerios'
    | '/ministerios/$slug/$secao'
    | '/ministerios/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/administracao'
    | '/agenda'
    | '/avisos'
    | '/cadastro'
    | '/caixa'
    | '/estudo'
    | '/login'
    | '/mais'
    | '/ministerios'
    | '/oracao'
    | '/pastoral'
    | '/_authenticated/perfil'
    | '/admin/avisos'
    | '/admin/membros'
    | '/culto/$dia'
    | '/ministerios/'
    | '/ministerios/$slug/$secao'
    | '/ministerios/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdministracaoRoute: typeof AdministracaoRoute
  AgendaRoute: typeof AgendaRoute
  AvisosRoute: typeof AvisosRoute
  CadastroRoute: typeof CadastroRoute
  CaixaRoute: typeof CaixaRoute
  EstudoRoute: typeof EstudoRoute
  LoginRoute: typeof LoginRoute
  MaisRoute: typeof MaisRoute
  MinisteriosRoute: typeof MinisteriosRouteWithChildren
  OracaoRoute: typeof OracaoRoute
  PastoralRoute: typeof PastoralRoute
  AdminAvisosRoute: typeof AdminAvisosRoute
  AdminMembrosRoute: typeof AdminMembrosRoute
  CultoDiaRoute: typeof CultoDiaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administracao': {
      id: '/administracao'
      path: '/administracao'
      fullPath: '/administracao'
      preLoaderRoute: typeof AdministracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avisos': {
      id: '/avisos'
      path: '/avisos'
      fullPath: '/avisos'
      preLoaderRoute: typeof AvisosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caixa': {
      id: '/caixa'
      path: '/caixa'
      fullPath: '/caixa'
      preLoaderRoute: typeof CaixaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudo': {
      id: '/estudo'
      path: '/estudo'
      fullPath: '/estudo'
      preLoaderRoute: typeof EstudoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mais': {
      id: '/mais'
      path: '/mais'
      fullPath: '/mais'
      preLoaderRoute: typeof MaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ministerios': {
      id: '/ministerios'
      path: '/ministerios'
      fullPath: '/ministerios'
      preLoaderRoute: typeof MinisteriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oracao': {
      id: '/oracao'
      path: '/oracao'
      fullPath: '/oracao'
      preLoaderRoute: typeof OracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pastoral': {
      id: '/pastoral'
      path: '/pastoral'
      fullPath: '/pastoral'
      preLoaderRoute: typeof PastoralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/avisos': {
      id: '/admin/avisos'
      path: '/admin/avisos'
      fullPath: '/admin/avisos'
      preLoaderRoute: typeof AdminAvisosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/membros': {
      id: '/admin/membros'
      path: '/admin/membros'
      fullPath: '/admin/membros'
      preLoaderRoute: typeof AdminMembrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/culto/$dia': {
      id: '/culto/$dia'
      path: '/culto/$dia'
      fullPath: '/culto/$dia'
      preLoaderRoute: typeof CultoDiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ministerios/': {
      id: '/ministerios/'
      path: '/'
      fullPath: '/ministerios/'
      preLoaderRoute: typeof MinisteriosIndexRouteImport
      parentRoute: typeof MinisteriosRoute
    }
    '/ministerios/$slug/': {
      id: '/ministerios/$slug/'
      path: '/$slug'
      fullPath: '/ministerios/$slug/'
      preLoaderRoute: typeof MinisteriosSlugIndexRouteImport
      parentRoute: typeof MinisteriosRoute
    }
    '/ministerios/$slug/$secao': {
      id: '/ministerios/$slug/$secao'
      path: '/$slug/$secao'
      fullPath: '/ministerios/$slug/$secao'
      preLoaderRoute: typeof MinisteriosSlugSecaoRouteImport
      parentRoute: typeof MinisteriosRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface MinisteriosRouteChildren {
  MinisteriosIndexRoute: typeof MinisteriosIndexRoute
  MinisteriosSlugSecaoRoute: typeof MinisteriosSlugSecaoRoute
  MinisteriosSlugIndexRoute: typeof MinisteriosSlugIndexRoute
}

const MinisteriosRouteChildren: MinisteriosRouteChildren = {
  MinisteriosIndexRoute: MinisteriosIndexRoute,
  MinisteriosSlugSecaoRoute: MinisteriosSlugSecaoRoute,
  MinisteriosSlugIndexRoute: MinisteriosSlugIndexRoute,
}

const MinisteriosRouteWithChildren = MinisteriosRoute._addFileChildren(
  MinisteriosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdministracaoRoute: AdministracaoRoute,
  AgendaRoute: AgendaRoute,
  AvisosRoute: AvisosRoute,
  CadastroRoute: CadastroRoute,
  CaixaRoute: CaixaRoute,
  EstudoRoute: EstudoRoute,
  LoginRoute: LoginRoute,
  MaisRoute: MaisRoute,
  MinisteriosRoute: MinisteriosRouteWithChildren,
  OracaoRoute: OracaoRoute,
  PastoralRoute: PastoralRoute,
  AdminAvisosRoute: AdminAvisosRoute,
  AdminMembrosRoute: AdminMembrosRoute,
  CultoDiaRoute: CultoDiaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
